name: Test Build

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    types: [cloased, opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn build
